#!/bin/bash
set -o pipefail

# Run Checkstyle
mvn checkstyle:check

# Run SpotBugs
mvn spotbugs:check

# Run PMD
mvn pmd:check

# Run Unit Tests and Checker Framework
mvn clean compile test

# Run JaCoCo
mvn jacoco:report

# Output New Jacoco Report with the Format:
echo ""
echo "JaCoCo Report"
INSTRUCTION=$(cat target/site/jacoco/index.html | grep -oP '(?<=<td class="ctr2">)\d+%' | head -n 1)
BRANCH=$(cat target/site/jacoco/index.html | grep -oP '(?<=<td class="ctr2">)\d+%' | tail -n 1)
INSTRUCTION_MISSED=$(cat target/site/jacoco/index.html | grep -oP '(?<=<td class="bar">)\d{1,3}(,\d{3})* of \d{1,3}(,\d{3})*' | head -n 1)
BRANCH_MISSED=$(cat target/site/jacoco/index.html | grep -oP '(?<=<td class="bar">)\d{1,3}(,\d{3})* of \d{1,3}(,\d{3})*' | tail -n 1)
echo "Instruction Coverage: $INSTRUCTION ($INSTRUCTION_MISSED missed)"
echo "Branch Coverage: $BRANCH ($BRANCH_MISSED missed)"
echo "Report is available at target/site/jacoco/index.html"
