name: Java CI with Maven

on:
  push:
    branches: ["dummy"]
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    name: Maven Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: temurin
        cache: maven
    - name: Run the Maven tests & Checker Framework
      run: mvn clean compile test
    - name: Run Spotbugs
      run: mvn spotbugs:check
    - name: Run Checkstyle
      run: mvn checkstyle:check
    - name: Run PMD tests
      run: mvn pmd:check
    - name: Run Jacoco
      run: mvn jacoco:report
    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.0
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 100
        update-comment: true
        title: '# :bar_chart: Coverage Report'
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'
